{% set version = "0.1.0" %}

package:
  name: hadoop-test-cluster
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hadoop-test-cluster/hadoop-test-cluster-{{ version }}.tar.gz
  sha256: b72948f296c0537b9800f8b7befb2806bbbd99de3b54656ccb8bdb7be99b4424

build:
  skip: True  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - hadoop_test_cluster

about:
  home: https://github.com/jcrist/hadoop-test-cluster
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A dockerized setup for testing code on realistic hadoop clusters

extra:
  recipe-maintainers:
    - raybellwaves
